### ISSUE TITLE
Problem z responsywnością

### ISSUE THREAD

**Issue by Suvres** [phajder/ask-node-react-docker#1]
Dzień dobry,
w Pana stronie responsywność zakłuca przebieg doświadczenia, ponieważ w pliku 
[Layout.jsx](https://github.com/phajder/ask-node-react-docker/blob/master/client/src/components/Layout/Layout.jsx) jest nadmiarowa klasa `hide-on-med-and-down` która przy pracy innej niż na pełnym ekranie usuwa przyciski, co powoduje, że nie można uruchomić usługi pobierania czy czyszczenia danych

**Comment by phajder** [comment]
Dodałem sidenav zamiast usuwania w przypadku mniejszych ekranów. Z jakiegoś powodu dodałem tą klasę kiedyś jako fix. Czego fix? Nie umiem już zweryfikować. : (
